#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'

cookbook 'sakurra_demo', path: './site-cookbooks/sakurra_demo'
cookbook 'td-agent', git: 'https://github.com/treasure-data/chef-td-agent.git'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
